/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./frontend/**/*.html",
    "./frontend/js/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        "primary":                   "#944931",
        "on-primary":                "#ffffff",
        "primary-fixed":             "#ffdbd0",
        "primary-fixed-dim":         "#ffb59e",
        "on-primary-fixed":          "#3a0b00",
        "on-primary-fixed-variant":  "#76321c",
        "primary-container":         "#d67d61",
        "on-primary-container":      "#551905",
        "secondary":                 "#4c616c",
        "on-secondary":              "#ffffff",
        "secondary-fixed":           "#cfe6f3",
        "secondary-fixed-dim":       "#b3cad6",
        "on-secondary-fixed":        "#061e27",
        "on-secondary-fixed-variant":"#344a54",
        "secondary-container":       "#cce3f0",
        "on-secondary-container":    "#506670",
        "tertiary":                  "#80515e",
        "on-tertiary":               "#ffffff",
        "tertiary-fixed":            "#ffd9e1",
        "tertiary-fixed-dim":        "#f3b6c6",
        "on-tertiary-fixed":         "#330f1c",
        "on-tertiary-fixed-variant": "#653a47",
        "tertiary-container":        "#bc8694",
        "on-tertiary-container":     "#48212d",
        "surface":                   "#fbf9f4",
        "surface-dim":               "#dbdad5",
        "surface-bright":            "#fbf9f4",
        "surface-container-lowest":  "#ffffff",
        "surface-container-low":     "#f5f3ee",
        "surface-container":         "#f0eee9",
        "surface-container-high":    "#eae8e3",
        "surface-container-highest": "#e4e2dd",
        "surface-variant":           "#e4e2dd",
        "surface-tint":              "#944931",
        "on-surface":                "#1b1c19",
        "on-surface-variant":        "#54433e",
        "background":                "#fbf9f4",
        "on-background":             "#1b1c19",
        "outline":                   "#87736d",
        "outline-variant":           "#dac1ba",
        "inverse-surface":           "#30312e",
        "inverse-on-surface":        "#f2f1ec",
        "inverse-primary":           "#ffb59e",
        "error":                     "#ba1a1a",
        "on-error":                  "#ffffff",
        "error-container":           "#ffdad6",
        "on-error-container":        "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
      },
      spacing: {
        "margin-desktop":  "64px",
        "margin-mobile":   "20px",
        "container-max":   "1280px",
        "max-width-layout":"1280px",
        "max-width-content":"800px",
        "gutter":          "24px",
        "unit":            "8px",
      },
      fontFamily: {
        "body-lg":          ["Plus Jakarta Sans", "sans-serif"],
        "body-md":          ["Plus Jakarta Sans", "sans-serif"],
        "headline-md":      ["Literata", "serif"],
        "headline-lg":      ["Literata", "serif"],
        "headline-lg-mobile":["Literata", "serif"],
        "label-md":         ["Plus Jakarta Sans", "sans-serif"],
        "caption":          ["Plus Jakarta Sans", "sans-serif"],
        "display-lg":       ["Literata", "serif"],
      },
      fontSize: {
        "body-lg":        ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md":        ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md":    ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg":    ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile":["28px", { lineHeight: "36px", fontWeight: "600" }],
        "label-md":       ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "caption":        ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "display-lg":     ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max":   "1280px",
        "content":         "800px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
